// Export Dashboard - Data export for state audits
// Amanda can download all Compass data with integrity hashes for state inspection.

import { useState, useEffect, useCallback } from 'react';
import {
  Download,
  FileJson,
  FileSpreadsheet,
  Shield,
  ShieldCheck,
  AlertTriangle,
  Clock,
  RefreshCw,
  Database,
  Users,
  CalendarDays,
  MessageCircle,
  BookOpen,
  Activity,
  FileText,
} from 'lucide-react';

const COMPASS_API_URL = import.meta.env.VITE_COMPASS_API_URL || 'https://replaybrick.com';
const API_KEY = import.meta.env.VITE_COMPASS_API_KEY || 'spring-vicki-2026';

// Map data keys to human labels and icons
const DATA_TYPE_META = {
  contacts: { label: 'Contacts', icon: Users, description: 'Residents, family, doctors, staff' },
  events: { label: 'Calendar Events', icon: CalendarDays, description: 'Scheduled activities and events' },
  chatHistory: { label: 'Chat History', icon: MessageCircle, description: 'Conversations with Spring AI' },
  books: { label: 'Books', icon: BookOpen, description: "Amanda's reading list" },
  activityLogs: { label: 'Activity Logs', icon: Activity, description: 'Resident activity records' },
  residents: { label: 'Residents', icon: Database, description: 'Resident profiles and details' },
};

function getDataTypeMeta(key) {
  return DATA_TYPE_META[key] || { label: key, icon: FileText, description: 'Data store' };
}

async function apiFetch(path, options = {}) {
  const url = `${COMPASS_API_URL}${path}`;
  const res = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': API_KEY,
      ...(options.headers || {}),
    },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` }));
    throw new Error(err.error || `HTTP ${res.status}`);
  }
  return res;
}

export default function ExportDashboard() {
  const [dataKeys, setDataKeys] = useState([]);
  const [auditMode, setAuditMode] = useState(true); // Default: state-audit mode ON
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(null); // key being exported, or 'all'
  const [error, setError] = useState(null);
  const [blobStatus, setBlobStatus] = useState(null);
  const [exportHistory, setExportHistory] = useState([]);

  const loadData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      // Fetch data keys
      const keysRes = await apiFetch('/api/data');
      const { keys } = await keysRes.json();
      const filtered = (keys || []).filter(k => !k.startsWith('__'));
      setDataKeys(filtered);

      // Fetch blob status
      try {
        const statusRes = await apiFetch('/api/data/status');
        setBlobStatus(await statusRes.json());
      } catch (e) {
        setBlobStatus({ error: e.message });
      }
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  async function handleExport(key) {
    setExporting(key);
    setError(null);
    try {
      const res = await apiFetch(`/api/data/export?format=json&keys=${key}`);
      const data = await res.json();

      // Download as JSON file
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compass-${key}-${data.exportedAt.slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);

      setExportHistory(prev => [{
        key,
        time: new Date().toISOString(),
        hash: data.dataHash?.slice(0, 12),
        count: data.recordCounts?.[key] || 0,
      }, ...prev].slice(0, 20));
    } catch (e) {
      setError(`Export failed: ${e.message}`);
    } finally {
      setExporting(null);
    }
  }

  async function handleExportAll() {
    setExporting('all');
    setError(null);
    try {
      const res = await apiFetch('/api/data/export?format=json&keys=all');
      const data = await res.json();

      if (auditMode) {
        // Add cover sheet for state audit
        data._coverSheet = {
          title: 'Compass Data Export — State Audit Record',
          exportedAt: data.exportedAt,
          exportedBy: 'Spring v2.0 (Netlify Blobs)',
          dataHash: data.dataHash,
          keyCount: data.keyCount,
          recordCounts: data.recordCounts,
          certification: 'This export was generated by the Compass Activities Management System. '
            + 'Data integrity is verified by SHA-256 hash. Any tampering will invalidate the hash. '
            + 'This record is suitable for state regulatory audit purposes.',
        };
      }

      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compass-full-export-${data.exportedAt.slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);

      setExportHistory(prev => [{
        key: 'all',
        time: new Date().toISOString(),
        hash: data.dataHash?.slice(0, 12),
        count: data.keyCount,
      }, ...prev].slice(0, 20));
    } catch (e) {
      setError(`Export failed: ${e.message}`);
    } finally {
      setExporting(null);
    }
  }

  async function handleExportCSV(key) {
    setExporting(key);
    setError(null);
    try {
      const res = await apiFetch(`/api/data/export?format=csv&keys=${key}`);
      const text = await res.text();
      const blob = new Blob([text], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `compass-${key}-${new Date().toISOString().slice(0, 10)}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(`CSV export failed: ${e.message}`);
    } finally {
      setExporting(null);
    }
  }

  if (loading) {
    return (
      <div className="p-6 max-w-4xl mx-auto">
        <div className="flex items-center gap-3 text-violet-400">
          <RefreshCw size={20} className="animate-spin" />
          <span>Loading data stores...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 sm:p-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-violet-100 flex items-center justify-center">
            {auditMode ? (
              <ShieldCheck size={22} className="text-violet-600" />
            ) : (
              <Download size={22} className="text-violet-600" />
            )}
          </div>
          <div>
            <h1 className="text-2xl font-bold text-violet-300">Data Export</h1>
            <p className="text-violet-400 text-sm">
              {auditMode ? 'State audit mode — includes integrity hashes and cover sheet' : 'Download your data'}
            </p>
          </div>
        </div>
      </div>

      {/* Audit mode toggle + Export All */}
      <div className="flex flex-wrap items-center gap-3 mb-6">
        <button
          onClick={() => setAuditMode(!auditMode)}
          className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all ${
            auditMode
              ? 'bg-emerald-50 border border-emerald-200 text-emerald-700 shadow-sm'
              : 'bg-violet-50 border border-violet-200 text-violet-600'
          }`}
        >
          {auditMode ? <ShieldCheck size={18} /> : <Shield size={18} />}
          {auditMode ? 'Audit Mode: ON' : 'Audit Mode: OFF'}
        </button>

        <button
          onClick={handleExportAll}
          disabled={exporting === 'all'}
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-violet-600 text-white font-medium text-sm hover:bg-violet-500 transition-colors disabled:opacity-50 shadow-sm"
        >
          {exporting === 'all' ? (
            <RefreshCw size={18} className="animate-spin" />
          ) : (
            <Download size={18} />
          )}
          Export All Data
        </button>

        <button
          onClick={loadData}
          className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs text-violet-500 hover:text-violet-300 hover:bg-violet-50 transition-colors"
        >
          <RefreshCw size={14} />
          Refresh
        </button>
      </div>

      {/* Error */}
      {error && (
        <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-xl flex items-start gap-3">
          <AlertTriangle size={18} className="text-red-500 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-red-700 text-sm font-medium">Export Error</p>
            <p className="text-red-600 text-sm">{error}</p>
          </div>
        </div>
      )}

      {/* Blob status */}
      {blobStatus && (
        <div className={`mb-6 p-4 rounded-xl border text-sm ${
          blobStatus.durable
            ? 'bg-emerald-50 border-emerald-200'
            : 'bg-amber-50 border-amber-200'
        }`}>
          <div className="flex items-center gap-2 mb-1">
            <div className={`w-2 h-2 rounded-full ${blobStatus.durable ? 'bg-emerald-500' : 'bg-amber-500'}`} />
            <span className="font-medium text-gray-700">
              {blobStatus.durable ? 'Durable Storage Active' : 'Storage Warning'}
            </span>
          </div>
          <p className="text-gray-600">
            {blobStatus.durable
              ? 'Data is stored in Netlify Blobs — persistent and reliable for state audits.'
              : `Data storage mode: ${blobStatus.mode}. ${blobStatus.error || 'May not survive cold starts.'}`}
          </p>
        </div>
      )}

      {/* No data */}
      {dataKeys.length === 0 ? (
        <div className="text-center py-12 bg-violet-50 rounded-xl border border-violet-200">
          <Database size={40} className="mx-auto text-violet-300 mb-3" />
          <p className="text-violet-600 font-medium">No data stores found</p>
          <p className="text-violet-500 text-sm mt-1">Start using the Compass app to build up data for export.</p>
        </div>
      ) : (
        <>
          {/* Data store cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
            {dataKeys.map(key => {
              const meta = getDataTypeMeta(key);
              const Icon = meta.icon;
              return (
                <div
                  key={key}
                  className="bg-violet-50 rounded-xl border border-violet-200 shadow-sm overflow-hidden"
                >
                  <div className="p-4">
                    <div className="flex items-center gap-3 mb-3">
                      <div className="w-9 h-9 rounded-lg bg-violet-100 flex items-center justify-center">
                        <Icon size={18} className="text-violet-500" />
                      </div>
                      <div>
                        <h3 className="font-semibold text-violet-700">{meta.label}</h3>
                        <p className="text-xs text-violet-500">{meta.description}</p>
                      </div>
                    </div>

                    <div className="flex gap-2">
                      <button
                        onClick={() => handleExport(key)}
                        disabled={exporting === key}
                        className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg bg-violet-100 border border-violet-200 text-violet-700 text-xs font-medium hover:bg-violet-200 transition-colors disabled:opacity-50"
                      >
                        {exporting === key ? (
                          <RefreshCw size={14} className="animate-spin" />
                        ) : (
                          <FileJson size={14} />
                        )}
                        JSON
                      </button>
                      <button
                        onClick={() => handleExportCSV(key)}
                        disabled={exporting === key}
                        className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg bg-violet-100 border border-violet-200 text-violet-700 text-xs font-medium hover:bg-violet-200 transition-colors disabled:opacity-50"
                      >
                        <FileSpreadsheet size={14} />
                        CSV
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Export history */}
          {exportHistory.length > 0 && (
            <div className="bg-violet-50 rounded-xl border border-violet-200 shadow-sm overflow-hidden">
              <div className="px-5 py-3 border-b border-violet-200 flex items-center gap-2">
                <Clock size={16} className="text-violet-500" />
                <h2 className="font-semibold text-violet-700 text-sm">Recent Exports</h2>
              </div>
              <div className="divide-y divide-violet-200">
                {exportHistory.map((entry, i) => {
                  const meta = getDataTypeMeta(entry.key);
                  return (
                    <div key={i} className="px-5 py-2.5 flex items-center justify-between text-sm">
                      <div className="flex items-center gap-2">
                        <span className="text-violet-600 font-medium">
                          {entry.key === 'all' ? 'All Data' : meta.label}
                        </span>
                        {entry.hash && (
                          <span className="text-xs text-gray-400 font-mono">
                            SHA: {entry.hash}
                          </span>
                        )}
                      </div>
                      <span className="text-xs text-gray-500">
                        {new Date(entry.time).toLocaleString()}
                        {entry.count > 0 && ` · ${entry.count} records`}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
