redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/bbaxter/workspace/replay-bricks/website/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/bbaxter/workspace/replay-bricks/website"
command = "npm run build"

[build.environment]

[build.processing]
skip_processing = false

[build.processing.css]

[build.processing.html]
pretty_urls = true

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]